// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Routsky.Api.Data;

#nullable disable

namespace Routsky.Api.Migrations
{
    [DbContext(typeof(RoutskyDbContext))]
    partial class RoutskyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Routsky.Api.Entities.CityIntelligence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageMealCostUSD")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageTransportCostUSD")
                        .HasColumnType("double precision");

                    b.Property<string>("BestMonthsToVisit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CostOfLivingIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SafetyIndex")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CityIntelligences");
                });

            modelBuilder.Entity("Routsky.Api.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DailyCostLevel")
                        .HasColumnType("integer");

                    b.Property<string>("IataCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxRecommendedDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinRecommendedDays")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("PopularityWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Routsky.Api.Entities.GroupShortlistRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupShortlistRoutes");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RegionPriceTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CostLevel")
                        .HasColumnType("integer");

                    b.Property<int>("DailyBudgetUsdMax")
                        .HasColumnType("integer");

                    b.Property<int>("DailyBudgetUsdMin")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Region", "CostLevel")
                        .IsUnique();

                    b.ToTable("RegionPriceTiers");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteElimination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteQueryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("RouteQueryId");

                    b.ToTable("RouteEliminations");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BudgetBracket")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("HasSchengenVisa")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUkVisa")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUsVisa")
                        .HasColumnType("boolean");

                    b.Property<string>("Passports")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionPreference")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBudgetUsd")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RouteQueries");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedCostLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RecommendedDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("SavedRouteId")
                        .HasColumnType("uuid");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StopReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("SavedRouteId", "StopOrder")
                        .IsUnique();

                    b.ToTable("RouteStops");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupShortlistRouteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupShortlistRouteId");

                    b.HasIndex("UserId");

                    b.ToTable("RouteVotes");
                });

            modelBuilder.Entity("Routsky.Api.Entities.SavedRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RouteQueryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectionReason")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RouteQueryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("SavedRoutes");
                });

            modelBuilder.Entity("Routsky.Api.Entities.TravelGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.ToTable("TravelGroups");
                });

            modelBuilder.Entity("Routsky.Api.Entities.TravelGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("TravelGroupMembers");
                });

            modelBuilder.Entity("Routsky.Api.Entities.TraveledRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccommodationExpense")
                        .HasColumnType("integer");

                    b.Property<string>("DaySufficiencyJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodExpense")
                        .HasColumnType("integer");

                    b.Property<Guid>("SavedRouteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransportExpense")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TraveledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisaExperience")
                        .HasColumnType("integer");

                    b.Property<string>("WhatIWouldDoDifferently")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WhatWasChallenging")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("WhyThisRegion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SavedRouteId")
                        .IsUnique();

                    b.ToTable("TraveledRoutes");
                });

            modelBuilder.Entity("Routsky.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarBase64")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Routsky.Api.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("Budget")
                        .HasColumnType("integer");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Passports")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("PriceAlertsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureBase64")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TravelStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitPreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Routsky.Api.Entities.VisaMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassportCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisaStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VisaMatrices");
                });

            modelBuilder.Entity("Routsky.Api.Entities.VisaRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgProcessingDays")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("EVisaUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxStayDays")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PassportCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Requirement")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PassportCountryCode", "DestinationCountryCode")
                        .IsUnique();

                    b.ToTable("VisaRules");
                });

            modelBuilder.Entity("Routsky.Api.Entities.GroupShortlistRoute", b =>
                {
                    b.HasOne("Routsky.Api.Entities.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.TravelGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteElimination", b =>
                {
                    b.HasOne("Routsky.Api.Entities.Destination", "Destination")
                        .WithMany("Eliminations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.RouteQuery", "RouteQuery")
                        .WithMany("Eliminations")
                        .HasForeignKey("RouteQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("RouteQuery");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteQuery", b =>
                {
                    b.HasOne("Routsky.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteStop", b =>
                {
                    b.HasOne("Routsky.Api.Entities.Destination", "Destination")
                        .WithMany("RouteStops")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.SavedRoute", "SavedRoute")
                        .WithMany("Stops")
                        .HasForeignKey("SavedRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("SavedRoute");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteVote", b =>
                {
                    b.HasOne("Routsky.Api.Entities.GroupShortlistRoute", "ShortlistRoute")
                        .WithMany("Votes")
                        .HasForeignKey("GroupShortlistRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortlistRoute");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Routsky.Api.Entities.SavedRoute", b =>
                {
                    b.HasOne("Routsky.Api.Entities.RouteQuery", "RouteQuery")
                        .WithMany("SavedRoutes")
                        .HasForeignKey("RouteQueryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.UserProfile", null)
                        .WithMany("SavedRoutes")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("RouteQuery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Routsky.Api.Entities.TravelGroupMember", b =>
                {
                    b.HasOne("Routsky.Api.Entities.TravelGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Routsky.Api.Entities.User", null)
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId1");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Routsky.Api.Entities.TraveledRoute", b =>
                {
                    b.HasOne("Routsky.Api.Entities.SavedRoute", "SavedRoute")
                        .WithOne("TraveledRoute")
                        .HasForeignKey("Routsky.Api.Entities.TraveledRoute", "SavedRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedRoute");
                });

            modelBuilder.Entity("Routsky.Api.Entities.UserProfile", b =>
                {
                    b.HasOne("Routsky.Api.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Routsky.Api.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Routsky.Api.Entities.Destination", b =>
                {
                    b.Navigation("Eliminations");

                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("Routsky.Api.Entities.GroupShortlistRoute", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Routsky.Api.Entities.RouteQuery", b =>
                {
                    b.Navigation("Eliminations");

                    b.Navigation("SavedRoutes");
                });

            modelBuilder.Entity("Routsky.Api.Entities.SavedRoute", b =>
                {
                    b.Navigation("Stops");

                    b.Navigation("TraveledRoute");
                });

            modelBuilder.Entity("Routsky.Api.Entities.TravelGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Routsky.Api.Entities.User", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Routsky.Api.Entities.UserProfile", b =>
                {
                    b.Navigation("SavedRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
