@Navisio.Api_HostAddress = http://localhost:5107

GET {{Navisio.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Navisio.Api_HostAddress}}/api/decision/discover
Content-Type: application/json

{
  "passport": "TR",
  "budgetLimit": "< $1500",
  "duration": "5–7 days",
  "region": "Europe"
}
